export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { sql } from '@/lib/db'
import { isValidIso } from '@/lib/utils'
import { detectPassages } from '@/lib/detector'

interface IngestReading {
  ts: string
  db_raw: number
  tram_flag?: boolean
}

interface IngestBody {
  source?: string        // 'interior' | 'exterior' — defaults to 'interior'
  device_id?: string     // stable UUID generated by the browser (localStorage)
  device_label?: string  // human-readable label set by the user
  readings: IngestReading[]
}

// Browser-side ingest — no API key (browser can't hold secrets).
// Source ('interior'/'exterior') is caller-supplied; device identity is optional metadata.
export async function POST(req: NextRequest) {
  let body: IngestBody
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  if (!Array.isArray(body.readings) || body.readings.length === 0) {
    return NextResponse.json({ error: 'readings must be a non-empty array' }, { status: 400 })
  }
  if (body.readings.length > 30) {
    return NextResponse.json({ error: 'readings batch must not exceed 30 items' }, { status: 400 })
  }

  // Accept any valid source name (alphanumeric / dash / underscore, ≤32 chars)
  const rawSource = typeof body.source === 'string' ? body.source.trim() : ''
  const source = /^[a-zA-Z0-9_-]{1,32}$/.test(rawSource) ? rawSource : 'default'
  const deviceId    = typeof body.device_id    === 'string' ? body.device_id.slice(0, 64)  : null
  const deviceLabel = typeof body.device_label === 'string' ? body.device_label.slice(0, 64) : null

  // Validate format strictly but skip out-of-range readings (rather than
  // aborting the whole batch — one bad reading should not discard all others).
  const valid: IngestReading[] = []
  for (const r of body.readings) {
    if (!isValidIso(r.ts)) continue
    if (typeof r.db_raw !== 'number' || !isFinite(r.db_raw)) continue
    if (r.db_raw < -60 || r.db_raw > 200) continue   // skip implausible values
    valid.push(r)
  }
  if (valid.length === 0) {
    return NextResponse.json({ error: 'No valid readings in batch' }, { status: 400 })
  }

  // Auto-create tables on first use (before /api/setup is run)
  await sql`
    CREATE TABLE IF NOT EXISTS readings (
      id           BIGSERIAL PRIMARY KEY,
      ts           TIMESTAMPTZ NOT NULL,
      source       TEXT NOT NULL,
      db_raw       REAL NOT NULL,
      db_cal       REAL,
      tram_flag    BOOLEAN DEFAULT FALSE,
      tram_line    TEXT,
      tram_stop    TEXT,
      tram_dir     TEXT,
      device_id    TEXT,
      device_label TEXT
    )
  `
  // Migrations for existing tables
  await sql`ALTER TABLE readings ADD COLUMN IF NOT EXISTS device_id    TEXT`
  await sql`ALTER TABLE readings ADD COLUMN IF NOT EXISTS device_label TEXT`
  // Drop the old binary-source check constraint so any source name is accepted
  await sql`ALTER TABLE readings DROP CONSTRAINT IF EXISTS readings_source_check`

  await sql`
    CREATE TABLE IF NOT EXISTS device_calibrations (
      id           BIGSERIAL PRIMARY KEY,
      session_id   BIGINT,
      source       TEXT NOT NULL,
      mean_db      REAL NOT NULL,
      offset_db    REAL NOT NULL DEFAULT 0,
      sample_count INT NOT NULL DEFAULT 0,
      active       BOOLEAN DEFAULT TRUE,
      created_at   TIMESTAMPTZ DEFAULT NOW()
    )
  `

  let offsetDb = 0
  try {
    const calibRows = await sql`
      SELECT offset_db FROM device_calibrations
      WHERE source = ${source} AND active = TRUE
      ORDER BY created_at DESC LIMIT 1
    `
    if (calibRows.length > 0) offsetDb = calibRows[0].offset_db as number
  } catch { /* non-fatal */ }

  let inserted = 0
  for (const r of valid) {
    const dbCal = r.db_raw + offsetDb
    await sql`
      INSERT INTO readings (ts, source, db_raw, db_cal, tram_flag, device_id, device_label)
      VALUES (${r.ts}, ${source}, ${r.db_raw}, ${dbCal}, ${r.tram_flag === true}, ${deviceId}, ${deviceLabel})
    `
    inserted++
  }

  // ── Tram detection ─────────────────────────────────────────────────────
  // Fetch causal look-back: last 120 readings for this source (covers
  // BG_WIN=30 + VOTE_WIN=10 warm-up plus the freshly-inserted batch).
  let flaggedCount = 0
  try {
    const lookback = (await sql`
      SELECT id, ts, db_cal, db_raw
      FROM readings
      WHERE source = ${source}
      ORDER BY ts DESC
      LIMIT 120
    `) as { id: bigint; ts: string; db_cal: number | null; db_raw: number }[]
    const window = lookback.reverse().map(r => ({
      id:   r.id,
      tsMs: new Date(r.ts).getTime(),
      db:   r.db_cal ?? r.db_raw,
    }))

    const passages = detectPassages(window)
    const ids = passages.flatMap(p => p.readingIds)
    const numericIds = ids.map(id => Number(id))

    if (numericIds.length > 0) {
      await sql`
        UPDATE readings
        SET tram_flag = TRUE
        WHERE id = ANY(${numericIds}) AND tram_flag = FALSE
      `
      flaggedCount = numericIds.length
    }
  } catch (err) {
    console.error('browser-ingest: tram detection failed (non-fatal)', err)
  }

  return NextResponse.json({
    inserted,
    offset_applied: offsetDb,
    source,
    device_id: deviceId,
    tram_flagged: flaggedCount,
  })
}
